'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DémarchesSimplifiées.RPA.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mutation dossierAccepter($input: DossierAccepterInput!) {
        '''	dossierAccepter(input: $input) {
        '''		dossier {
        '''			id
        '''		}
        '''		errors {
        '''			message
        '''		}
        '''	}
        '''}
        '''.
        '''</summary>
        Friend ReadOnly Property dossierAccepter() As String
            Get
                Return ResourceManager.GetString("dossierAccepter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mutation dossierClasserSansSuite($input: DossierClasserSansSuiteInput!) {
        '''	dossierClasserSansSuite(input: $input) {
        '''		dossier {
        '''			id
        '''		}
        '''		errors {
        '''			message
        '''		}
        '''	}
        '''}
        '''.
        '''</summary>
        Friend ReadOnly Property dossierClasserSansSuite() As String
            Get
                Return ResourceManager.GetString("dossierClasserSansSuite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mutation dossierModifierAnnotationAjouterLigne($input: DossierModifierAnnotationAjouterLigneInput!) {
        '''	dossierModifierAnnotationAjouterLigne(input: $input) {
        '''	}
        '''}.
        '''</summary>
        Friend ReadOnly Property dossierModifierAnnotationAjouterLigne() As String
            Get
                Return ResourceManager.GetString("dossierModifierAnnotationAjouterLigne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mutation dossierPasserEnInstruction($input: DossierPasserEnInstructionInput!) {
        '''	dossierPasserEnInstruction(input: $input) {
        '''		dossier {
        '''			id
        '''		}
        '''		errors {
        '''			message
        '''		}
        '''	}
        '''}
        '''.
        '''</summary>
        Friend ReadOnly Property dossierPasserEnInstruction() As String
            Get
                Return ResourceManager.GetString("dossierPasserEnInstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mutation dossierRefuser($input: DossierRefuserInput!) {
        '''	dossierRefuser(input: $input) {
        '''		dossier {
        '''			id
        '''		}
        '''		errors {
        '''			message
        '''		}
        '''	}
        '''}
        '''.
        '''</summary>
        Friend ReadOnly Property dossierRefuser() As String
            Get
                Return ResourceManager.GetString("dossierRefuser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mutation dossierRepasserEnConstruction($input: DossierRepasserEnConstructionInput!) {
        '''	dossierRepasserEnConstruction(input: $input) {
        '''		dossier {
        '''			id
        '''		}
        '''		errors {
        '''			message
        '''		}
        '''	}
        '''}
        '''.
        '''</summary>
        Friend ReadOnly Property dossierRepasserEnConstruction() As String
            Get
                Return ResourceManager.GetString("dossierRepasserEnConstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mutation dossierRepasserEnInstruction($input: DossierRepasserEnInstructionInput!) {
        '''	dossierRepasserEnInstruction(input: $input) {
        '''		dossier {
        '''			id
        '''		}
        '''		errors {
        '''			message
        '''		}
        '''	}
        '''}
        '''.
        '''</summary>
        Friend ReadOnly Property dossierRepasserEnInstruction() As String
            Get
                Return ResourceManager.GetString("dossierRepasserEnInstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à query getDemarche(
        '''	$demarcheNumber: Int!
        '''	$first: Int
        '''	$state: DossierState
        '''	$order: Order
        '''	$after: String
        ''') {
        '''	demarche(number: $demarcheNumber) {
        '''		id
        '''		number
        '''		title
        '''		dossiers(first: $first, state: $state, order: $order, after: $after) {
        '''			pageInfo {
        '''				endCursor
        '''				hasNextPage
        '''			}
        '''			nodes {
        '''				id
        '''				number
        '''				state
        '''				dateDepot
        '''				dateTraitement
        '''				demandeur {
        '''					id
        '''					...on PersonneMorale {
        '''						address {
        '''							cityCode
        '''							cityName
        '''							departmentCo [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property getDemarche() As String
            Get
                Return ResourceManager.GetString("getDemarche", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à  query getDossier(
        '''    $dossierNumber: Int!
        '''    $includeRevision: Boolean = false
        '''    $includeService: Boolean = false
        '''    $includeChamps: Boolean = true
        '''    $includeAnotations: Boolean = true
        '''    $includeTraitements: Boolean = true
        '''    $includeInstructeurs: Boolean = true
        '''    $includeAvis: Boolean = false
        '''    $includeMessages: Boolean = true
        '''    $includeGeometry: Boolean = true
        '''  ) {
        '''    dossier(number: $dossierNumber) {
        '''      ...DossierFragment
        '''      demarche {
        '''        ...DemarcheDescriptor [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property getDossier() As String
            Get
                Return ResourceManager.GetString("getDossier", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
